rework

diff --git a/xinit-application/src/main/resources/var/lib/xinit/check-xwiki-install b/xinit-application/src/main/resources/var/lib/xinit/check-xwiki-install
--- a/xinit-application/src/main/resources/var/lib/xinit/check-xwiki-install
+++ b/xinit-application/src/main/resources/var/lib/xinit/check-xwiki-install
@@ -2,112 +2,128 @@
 
 check_install ()
 {
-	log "INFO" "Starting a complete installation check"
+    log "INFO" "Starting installation check for ${CONTAINER_TYPE} ${CONTAINER_VERSION}"
     check_xwiki
-    check_apache
-    check_tomcat
+    check_container
     check_java
-    check_mysql
+    check_database
+    check_systemd
 }
 
 check_xwiki ()
 {
+    if [[ ! -d "${XWIKI_INSTALL_DIR}" ]]; then
+        log "WARNING" "XWiki directory not found at ${XWIKI_INSTALL_DIR}"
+        return
+    fi
 
-if [[ ! -h ${XWIKI_HOME} ]]; then
+    if [[ ! -f "${XWIKI_INSTALL_DIR}/WEB-INF/xwiki.cfg" ]]; then
+        log "WARNING" "xwiki.cfg not found in ${XWIKI_INSTALL_DIR}/WEB-INF/"
+        return
+    fi
 
-	log "WARNING" "The XWiki directory seems not installed, XWiki should be installed in /usr/local/"
-        
-	elif [[ ! -f ${XWIKI_INIT} ]]; then
+    if ! grep -q "xwiki.encoding.*=.*UTF-8" "${XWIKI_INSTALL_DIR}/WEB-INF/xwiki.cfg"; then
+        log "WARNING" "xwiki.cfg may not be configured for UTF-8 encoding"
+    fi
 
-		log "WARNING" "Daemon script xwiki.sh is not in place (you should put in /etc/init.d/)"
+    if [[ -f "${XWIKI_INSTALL_DIR}/WEB-INF/hibernate.cfg.xml" ]]; then
+        if ! grep -q 'connection.useUnicode">true' "${XWIKI_INSTALL_DIR}/WEB-INF/hibernate.cfg.xml"; then
+            log "WARNING" "hibernate.cfg.xml may not be configured for UTF-8 encoding"
+        fi
+    fi
 
-	if [[ ! -x ${XWIKI_INIT} ]]; then
-        
-		log "WARNING" "The daemon script xwiki.sh is not executable. You must add execute permission for all users!"
-	fi
-	
-	#if [ $(ls /etc/rc?.d/*tomcat.sh | grep -E 'rc0|rc1|rc2|rc3|rc4|rc5|rc6' | wc -l) = '7' ]; then 
-	if [ "$(find /etc/rc[0123456].d/*tomcat.sh | wc -l)" = '7' ]; then 
-
-		log "WARNING" "Daemon script isn't added to rc.d... It won't be started to system launch."
-	fi
-    
-	
-	if [ "$(grep "xwiki.encoding.*=.*UTF-8" "${XWIKI_HOME}"/WEB-INF/xwiki.cfg)" == "" ]; then
-
-		log "WARNING" "xinit.cfg seems not to be configured for UTF-8 encoding. Check it!"
-	fi
-
-	if [[ "$(grep '<property name="connection.useUnicode">true</property>' "${XWIKI_HOME}"/WEB-INF/hibernate.cfg.xml)" == "" || "$(grep '<property name="connection.characterEncoding">UTF-8</property>' "${XWIKI_HOME}"/WEB-INF/hibernate.cfg.xml)" == "" ]]; then
-
-		log "WARNING" "Hibernate.cfg.xml seems not to be configured for UTF-8 encoding"
-	fi
-fi
-
+    log "INFO" "XWiki installation check passed"
 }
 
-check_apache ()
+check_container ()
 {
-
-if [[ ! -f /etc/init.d/apache2 ]]; then
-
-                log "INFO" "Apache2 is not installed on the server"
-
-        elif [[  ! -f /etc/apache2/mods-enabled/proxy_ajp.load ]]; then
-
-                log "WARNING" "The AJP proxy module isn't activated on the server"
-
-        if [[ ! -f /etc/apache2/mods-enabled/proxy_http.load ]]; then 
-
-		log "WARNING" "The HTTP proxy module isn't activated on the server"
-	fi
-fi
+    case "${CONTAINER_TYPE}" in
+        "jetty")
+            if [[ ! -d "${CONTAINER_HOME}" ]]; then
+                log "WARNING" "Jetty home not found at ${CONTAINER_HOME}"
+                return
+            fi
+            if [[ ! -f "${START_SCRIPT}" ]]; then
+                log "WARNING" "Jetty start script not found at ${START_SCRIPT}"
+                return
+            fi
+            log "INFO" "Jetty installation check passed"
+            ;;
+        "tomcat")
+            if [[ ! -d "${CONTAINER_HOME}" ]]; then
+                log "WARNING" "Tomcat home not found at ${CONTAINER_HOME}"
+                return
+            fi
+            if [[ ! -f "${CONTAINER_HOME}/bin/catalina.sh" ]]; then
+                log "WARNING" "catalina.sh not found in ${CONTAINER_HOME}/bin/"
+                return
+            fi
+            if [[ -f "${CONTAINER_HOME}/conf/server.xml" ]] && ! grep -q 'URIEncoding.*=.*"UTF-8"' "${CONTAINER_HOME}/conf/server.xml"; then
+                log "WARNING" "Tomcat may not be configured for UTF-8 encoding in server.xml"
+            fi
+            log "INFO" "Tomcat installation check passed"
+            ;;
+    esac
 }
 
-check_tomcat ()
+check_systemd ()
 {
+    if ! systemctl list-unit-files | grep -q "^${SERVICE_NAME}"; then
+        log "WARNING" "Systemd service ${SERVICE_NAME} not found"
+        log "WARNING" "Run 'xinit setup-systemd' to create configuration"
+        return
+    fi
 
-if [[ ! -L ${TOMCAT_HOME} ]]; then
-
-          log "WARNING" "The Tomcat directory seems not created or ${TOMCAT_HOME} si not an sym link!"
-	  log "WARNING"	"${TOMCAT_HOME} should be a symlink to Tomcat install directory"
-
-fi
-
-if [  "$(grep 'URIEncoding.*=.*"UTF-8"' "${TOMCAT_HOME}"/conf/server.xml)" == "" ]; then
-
-          log "WARNING" "Tomcat seems not to be configured for UTF-8 encoding"
-
-fi
-
-
+    log "INFO" "Systemd service check passed: ${SERVICE_NAME}"
 }
 
 check_java ()
 {
+    if [[ -z "${JAVA_HOME}" ]] || [[ ! -d "${JAVA_HOME}" ]]; then
+        log "WARNING" "JAVA_HOME not set or directory not found: ${JAVA_HOME}"
+        return
+    fi
 
-if [[ ! -e ${JAVA_HOME} ]]; then
+    if [[ ! -x "${JAVA_HOME}/bin/java" ]]; then
+        log "WARNING" "Java executable not found at ${JAVA_HOME}/bin/java"
+        return
+    fi
 
-                log "WARNING" "JAVA isn't installed or isn't in the right place ( ${JAVA_HOME} ). "
-        fi
-
+    local java_version=$("${JAVA_HOME}/bin/java" -version 2>&1 | head -n 1)
+    log "INFO" "Java check passed: ${java_version}"
 }
 
-check_mysql ()
+check_database ()
 {
+    case "${DB_TYPE}" in
+        "mysql")
+            if ! command -v mysql &>/dev/null; then
+                log "WARNING" "MySQL client not found"
+                return
+            fi
 
-if [[ ! -f /etc/init.d/mysql ]]; then
+            if ! mysql -u"${MYSQL_USER}" --password="${MYSQL_PASSWORD}" -h"${MYSQL_HOST}" -e "SELECT 1;" &>/dev/null; then
+                log "WARNING" "Cannot connect to MySQL/MariaDB with configured credentials"
+                return
+            fi
 
-                log "INFO" "MySQL seems not be installed"
+            log "INFO" "MySQL/MariaDB connection check passed (user: ${MYSQL_USER})"
+            ;;
+        "pgsql")
+            if ! command -v psql &>/dev/null; then
+                log "WARNING" "PostgreSQL client not found"
+                return
+            fi
 
-        elif [ "$(grep "bind-address.*=.*0.0.0.0" "${MYSQL_HOME}"/my.cnf)" == "" ];then
+            if ! PGPASSWORD="${PGSQL_PASSWORD}" psql -U "${PGSQL_USER}" -h "${PGSQL_HOST}" -p "${PGSQL_PORT}" -d "${PGSQL_DATABASE}" -c "SELECT 1;" &>/dev/null; then
+                log "WARNING" "Cannot connect to PostgreSQL with configured credentials"
+                return
+            fi
 
-                log "INFO" "Mysql may not listen on all interfaces."
-        fi
-
-	if [[ "$(grep "character-set-server.*=.*utf8" "${MYSQL_HOME}"/my.cnf)" == "" || "$(grep "default-character-set.*=.*utf8" "${MYSQL_HOME}"/my.cnf)" == "" || "$(grep "collation-server.*=.*utf8_general_ci" "${MYSQL_HOME}"/my.cnf)" == "" ]];then
-
-		log "WARNING" "Mysql-server seems to be unconfigured for UTF-8. Check ${MYSQL_HOME}/my.cnf and add the utf-8 configuration for client & server"
-
-	fi
+            log "INFO" "PostgreSQL connection check passed (user: ${PGSQL_USER})"
+            ;;
+        "none")
+            log "INFO" "No database configured (DB_TYPE=none)"
+            ;;
+    esac
 }
